### ISSUE TITLE
update the original repo to point here

### ISSUE THREAD

**Issue by southbite** [node-swig/swig-templates#19]
Instead of just having NOT CURRENTLY MAINTAINED, how about having it point here. Also - I am definitely willing to put some time in here, love Swig, so if you are taking on any team members I would be happy to join and throw a couple of hours into bug-fixes/improvements.

**Comment by Lochlan** [comment]
The "original" repo is owned by @paularmstrong and [he is not interested in transferring his repo to us right now](https://github.com/node-swig/swig-templates/issues/7#issuecomment-198545871).

Glad to hear you like this project.  Please feel free to open a pull request with any bug fixes or improvements!
