### ISSUE TITLE
Where is source of version 2.0.1?

### ISSUE THREAD

**Issue by ruudud** [node-swig/swig-templates#27]
Currently, the latest version published to [npm is 2.0.1](https://www.npmjs.com/package/swig-templates), but the `package.json` in [master](https://github.com/node-swig/swig-templates/blob/efd40a04ecb929ec2840b46b6b09d8703662eebb/package.json) currently has `version: "2.0.0"`.

What's going on?

**Comment by cdaringe** [comment]
hmm. ya, that's troublesome.  sorry about that! i will test/publish a `2.0.2` that is in fact the master code.

**Comment by cdaringe** [comment]
closed by `2.0.2` & 7a0b2ee
