### ISSUE TITLE
problem with date

### ISSUE THREAD

**Issue by S1SYPHOS** [node-swig/swig-templates#34]
Hey there,
I hope you don't mind me asking this here, wasn't sure wether SO is the right place or not, but I am currently trying to figure out why `swig` doesn't accept my `date` call inside a loop, like this:

```html
{% for post in collections.posts %}
  ...
    <span class="post-date">{{ post.date | date('d M Y') }}</span>
  ...
{% endfor %}
```
This gives me `Unable to parse "post.date | date(&#39;d M Y&#39;)"`, while outside of loops / everywhere else it's just working fine. Background: I'm using [`metalsmith`](http://metalsmith.io) and have this problem with both `swig` and `swig-templates`. If I am missing something obvious: don't mind me asking, I'm still learning :icecream:

**Comment by cdaringe** [comment]
no sweat.

i took your exact template (sans "..." sets) and did the following.

```js
// test.js
'use strict'
const swig = require('swig-templates')
const output = swig.renderFile('./test.swig', {
  collections: {
    posts: [ { date: new Date() }, { date: new Date() } ]
  }
})
console.log(output)
```

```html
{% for post in collections.posts %}
    <span class="post-date">{{ post.date | date('d M Y') }}</span>
{% endfor %}
```

```html
$ node test.js
    <span class="post-date">08 Nov 2016</span>

    <span class="post-date">08 Nov 2016</span>
```

my guess is that you copied and pasted your `date` filter from somewhere, and some bogus characters ended up in your clipboard that your editor isn't rendering

**Comment by cdaringe** [comment]
http://www.ascii.cl/htmlcodes.htm

are you running in the browser or on node?

**Comment by S1SYPHOS** [comment]
node

**Comment by cdaringe** [comment]
okee doke.  yep, i test the above in node.  _something else_ is likely the matter.  feel free to bounce more ideas off of us

**Comment by S1SYPHOS** [comment]
Problem solved.
I changed extension from .md to .html and now it works - whereas all other files I got are written in markdown and everything's just going smoothly.

Thanks for your efforts, much appreciated.

**Comment by cdaringe** [comment]
hmmm... that sounds peculiar.  just to be thorough, i converted mine to `.md` and it still went ok.  something peculiar is still afoot possibly.  regardless, both of our _things_™ are in motion!

**Comment by S1SYPHOS** [comment]
checked encoding and everything, so weird ..
