### ISSUE TITLE
split filter

### ISSUE THREAD

**Issue by scippio** [node-swig/swig-templates#38]
```
"aaa;bbb"|split(";")
// => ["aaa","bbb"]
```
http://node-swig.github.io/swig-templates/docs/filters/#join
http://twig.sensiolabs.org/doc/filters/split.html

**Comment by cdaringe** [comment]
More info please

**Comment by scippio** [comment]
you must joking :)

**Comment by scippio** [comment]
Yes it's feature request, sorry, I thought that it was obvious.

**Comment by rockie** [comment]
Hi scippio, there is a swig-extras module (https://github.com/node-swig/swig-extras) which has already included the split filter you want. Just call the extras.useFilter(...) to enable extra filters. However, I agree with you it's a bit weird the builtin filters have “join” but no “split”.
