### ISSUE TITLE
pass js value inside swig variable

### ISSUE THREAD

**Issue by Ikhan** [node-swig/swig-templates#39]
Hi I'm having passing js value inside the swig variable. Is there any way of doing it. Thanks.

Currently I'm doing like this

<script>
$(function(){
if(variable == 'something'){
   {%set n = variable %} 
}
});
</script>

Thanks.

**Comment by Markkos89** [comment]
<script> $(function(){ if(variable == 'something'){ {% set n = variable %} } }); </script>
-                                                                                  ^
-                                                                                   |
-                                                                                   |
-                                                                                 here you have one blank space missing, try with the blank space
