### ISSUE TITLE
¿Why do I need to restart express server when I make a change to a swig template?

### ISSUE THREAD

**Issue by parakawa** [node-swig/swig-templates#43]
Every time I make a change to my .html file, I hope to only reload the page to see my changes. However, using swig, I have to restart the server. Is it a bug, or should I configure something additional?

Thanks.

**Comment by cdaringe** [comment]
hello, `swig` doesn't do caching on it's own.  that is--rendering is just a normal function.  most likely, some other layer on your server is reading in the template, caching it, and not updating on save.  good luck!

**Comment by cdaringe** [comment]
i don't use express, otherwise i'd lend more tips!
