### ISSUE TITLE
Suggest remove fork relation

### ISSUE THREAD

**Issue by JiangTJ** [node-swig/swig-templates#53]
Because it can't be searched in GitHub.
![image](https://user-images.githubusercontent.com/15902347/57365752-4231ec80-71b8-11e9-88c7-e54ada332990.png)
No node-swig/swig-templates !

**Comment by cdaringe** [comment]
sure thing, i'll ask github support

**Comment by cdaringe** [comment]
GitHub support has obliged and done as requested.  Thanks to them :)
