### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [node-swig/swig-templates#80]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by cdaringe** [comment]
Howdy. Ya, none of us are very active here anymore. Considering calling for new maintainers or archiving it outright

**Comment by JamieSlome** [comment]
@zidingz - are you up for maintaining this with me?

**Comment by zidingz** [comment]
@JamieSlome Yes sir!

**Comment by cdaringe** [comment]
🙇 godspeed. invite sent

**Comment by JamieSlome** [comment]
@cdaringe - will do! ❤️
